//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear clipboard in {0} seconds. ähnelt.
        /// </summary>
        public static string AUTO_CLEAR_CLIPBOARD_IN_0 {
            get {
                return ResourceManager.GetString("AUTO_CLEAR_CLIPBOARD_IN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear clipboard in 1 second. ähnelt.
        /// </summary>
        public static string AUTO_CLEAR_CLIPBOARD_IN_ONE {
            get {
                return ResourceManager.GetString("AUTO_CLEAR_CLIPBOARD_IN_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Copy ähnelt.
        /// </summary>
        public static string BUTTON_COPY_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_COPY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Exit ähnelt.
        /// </summary>
        public static string BUTTON_EXIT {
            get {
                return ResourceManager.GetString("BUTTON_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _New password ähnelt.
        /// </summary>
        public static string BUTTON_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected file has the wrong format. ähnelt.
        /// </summary>
        public static string ERROR_PWDGEN_INVALID_INPUT {
            get {
                return ResourceManager.GetString("ERROR_PWDGEN_INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Digits ähnelt.
        /// </summary>
        public static string LABEL_DIGITS {
            get {
                return ResourceManager.GetString("LABEL_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password: ähnelt.
        /// </summary>
        public static string LABEL_GENERATED_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_GENERATED_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lo_wer characters: ähnelt.
        /// </summary>
        public static string LABEL_LOWER_CHARS {
            get {
                return ResourceManager.GetString("LABEL_LOWER_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password _length: ähnelt.
        /// </summary>
        public static string LABEL_PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Symbols: ähnelt.
        /// </summary>
        public static string LABEL_SYMBOLS {
            get {
                return ResourceManager.GetString("LABEL_SYMBOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Upper characters: ähnelt.
        /// </summary>
        public static string LABEL_UPPER_CHARS {
            get {
                return ResourceManager.GetString("LABEL_UPPER_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password Generator ähnelt.
        /// </summary>
        public static string TITLE_GENERATE_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_GENERATE_PASSWORD", resourceCulture);
            }
        }
    }
}
