//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear clipboard in {0} seconds..
        /// </summary>
        public static string AUTO_CLEAR_CLIPBOARD_IN_0 {
            get {
                return ResourceManager.GetString("AUTO_CLEAR_CLIPBOARD_IN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear clipboard in 1 second..
        /// </summary>
        public static string AUTO_CLEAR_CLIPBOARD_IN_ONE {
            get {
                return ResourceManager.GetString("AUTO_CLEAR_CLIPBOARD_IN_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string BUTTON_COPY_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_COPY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string BUTTON_EXIT {
            get {
                return ResourceManager.GetString("BUTTON_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New password.
        /// </summary>
        public static string BUTTON_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file has the wrong format..
        /// </summary>
        public static string ERROR_PWDGEN_INVALID_INPUT {
            get {
                return ResourceManager.GetString("ERROR_PWDGEN_INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Digits.
        /// </summary>
        public static string LABEL_DIGITS {
            get {
                return ResourceManager.GetString("LABEL_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LABEL_GENERATED_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_GENERATED_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo_wer characters:.
        /// </summary>
        public static string LABEL_LOWER_CHARS {
            get {
                return ResourceManager.GetString("LABEL_LOWER_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password _length:.
        /// </summary>
        public static string LABEL_PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Symbols:.
        /// </summary>
        public static string LABEL_SYMBOLS {
            get {
                return ResourceManager.GetString("LABEL_SYMBOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Upper characters:.
        /// </summary>
        public static string LABEL_UPPER_CHARS {
            get {
                return ResourceManager.GetString("LABEL_UPPER_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generator.
        /// </summary>
        public static string TITLE_GENERATE_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_GENERATE_PASSWORD", resourceCulture);
            }
        }
    }
}
