//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear clipboard in {0} seconds..
        /// </summary>
        public static string AUTO_CLEAR_CLIPBOARD_IN_0 {
            get {
                return ResourceManager.GetString("AUTO_CLEAR_CLIPBOARD_IN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear clipboard in 1 second..
        /// </summary>
        public static string AUTO_CLEAR_CLIPBOARD_IN_ONE {
            get {
                return ResourceManager.GetString("AUTO_CLEAR_CLIPBOARD_IN_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide password in {0} seconds..
        /// </summary>
        public static string AUTO_HIDE_IN_0 {
            get {
                return ResourceManager.GetString("AUTO_HIDE_IN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide password in 1 second..
        /// </summary>
        public static string AUTO_HIDE_IN_ONE {
            get {
                return ResourceManager.GetString("AUTO_HIDE_IN_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upl_oad.
        /// </summary>
        public static string BUTTON_UPLOAD {
            get {
                return ResourceManager.GetString("BUTTON_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All passwords successfully uploaded..
        /// </summary>
        public static string CLOUD_UPLOAD_SUCCEEDED {
            get {
                return ResourceManager.GetString("CLOUD_UPLOAD_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string CMD_ABOUT {
            get {
                return ResourceManager.GetString("CMD_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add....
        /// </summary>
        public static string CMD_ADD {
            get {
                return ResourceManager.GetString("CMD_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change _key directory....
        /// </summary>
        public static string CMD_CHANGE_KEY_DIRECTORY {
            get {
                return ResourceManager.GetString("CMD_CHANGE_KEY_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change _master password....
        /// </summary>
        public static string CMD_CHANGE_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_CHANGE_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string CMD_CLOSE {
            get {
                return ResourceManager.GetString("CMD_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Upload passwords into cloud....
        /// </summary>
        public static string CMD_CLOUD_UPLOAD {
            get {
                return ResourceManager.GetString("CMD_CLOUD_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy _login to clipboard.
        /// </summary>
        public static string CMD_COPY_LOGIN {
            get {
                return ResourceManager.GetString("CMD_COPY_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy _password to clipboard.
        /// </summary>
        public static string CMD_COPY_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_COPY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string CMD_DELETE {
            get {
                return ResourceManager.GetString("CMD_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit....
        /// </summary>
        public static string CMD_EDIT {
            get {
                return ResourceManager.GetString("CMD_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string CMD_EXIT {
            get {
                return ResourceManager.GetString("CMD_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start password _generator.
        /// </summary>
        public static string CMD_GENERATE_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_GENERATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H_ide password.
        /// </summary>
        public static string CMD_HIDE_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_HIDE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New....
        /// </summary>
        public static string CMD_NEW {
            get {
                return ResourceManager.GetString("CMD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string CMD_OPEN {
            get {
                return ResourceManager.GetString("CMD_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open URL in browser.
        /// </summary>
        public static string CMD_OPEN_URL {
            get {
                return ResourceManager.GetString("CMD_OPEN_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Properties....
        /// </summary>
        public static string CMD_PROPERTIES {
            get {
                return ResourceManager.GetString("CMD_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string CMD_SAVE {
            get {
                return ResourceManager.GetString("CMD_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string CMD_SAVE_AS {
            get {
                return ResourceManager.GetString("CMD_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se_ttings....
        /// </summary>
        public static string CMD_SETTINGS {
            get {
                return ResourceManager.GetString("CMD_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _login column.
        /// </summary>
        public static string CMD_SHOW_LOGIN_COLUMN {
            get {
                return ResourceManager.GetString("CMD_SHOW_LOGIN_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show password.
        /// </summary>
        public static string CMD_SHOW_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_SHOW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pass_word column.
        /// </summary>
        public static string CMD_SHOW_PASSWORD_COLUMN {
            get {
                return ResourceManager.GetString("CMD_SHOW_PASSWORD_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _toolbar.
        /// </summary>
        public static string CMD_SHOW_TOOLBAR {
            get {
                return ResourceManager.GetString("CMD_SHOW_TOOLBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string COLUMN_LOGIN {
            get {
                return ResourceManager.GetString("COLUMN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string COLUMN_NAME {
            get {
                return ResourceManager.GetString("COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string COLUMN_PASSWORD {
            get {
                return ResourceManager.GetString("COLUMN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password specified or account is disabled..
        /// </summary>
        public static string ERROR_CLOUD_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("ERROR_CLOUD_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload password items..
        /// </summary>
        public static string ERROR_CLOUD_UPLOAD_FAILED {
            get {
                return ResourceManager.GetString("ERROR_CLOUD_UPLOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file has the wrong format..
        /// </summary>
        public static string ERROR_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key for &apos;{0}&apos; does not exist in the directory &apos;{1}&apos;..
        /// </summary>
        public static string ERROR_KEY_NOT_FOUND_0_1 {
            get {
                return ResourceManager.GetString("ERROR_KEY_NOT_FOUND_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. {0}.
        /// </summary>
        public static string ERROR_OCCURRED_0 {
            get {
                return ResourceManager.GetString("ERROR_OCCURRED_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not match..
        /// </summary>
        public static string ERROR_PASSWORD_DOES_NOT_MATCH {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_DOES_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least 4 characters..
        /// </summary>
        public static string ERROR_PASSWORD_MIN_CHARS {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_MIN_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is wrong..
        /// </summary>
        public static string ERROR_WRONG_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_WRONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password files (*.pwd)|*.pwd|All files (*.*)|*.*.
        /// </summary>
        public static string FILE_DIALOG_FILTER {
            get {
                return ResourceManager.GetString("FILE_DIALOG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_lear clipboard after (seconds):.
        /// </summary>
        public static string LABEL_AUTO_CLEAR_CLIPBOARD {
            get {
                return ResourceManager.GetString("LABEL_AUTO_CLEAR_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hide password after (seconds):.
        /// </summary>
        public static string LABEL_AUTO_HIDE_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_AUTO_HIDE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock window automatically.
        /// </summary>
        public static string LABEL_AUTOLOCK {
            get {
                return ResourceManager.GetString("LABEL_AUTOLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and minimize window.
        /// </summary>
        public static string LABEL_AUTOMINIMIZE {
            get {
                return ResourceManager.GetString("LABEL_AUTOMINIMIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Secret Key:.
        /// </summary>
        public static string LABEL_CLOUD_SECRET_KEY {
            get {
                return ResourceManager.GetString("LABEL_CLOUD_SECRET_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm m_aster password:.
        /// </summary>
        public static string LABEL_CONFIRM_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_onfirm new master password:.
        /// </summary>
        public static string LABEL_CONFIRM_NEW_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_NEW_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm passw_ord:.
        /// </summary>
        public static string LABEL_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Description:.
        /// </summary>
        public static string LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the master password for &apos;{0}&apos;..
        /// </summary>
        public static string LABEL_ENTER_MASTER_PASSWORD_FOR_0 {
            get {
                return ResourceManager.GetString("LABEL_ENTER_MASTER_PASSWORD_FOR_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:.
        /// </summary>
        public static string LABEL_KEY {
            get {
                return ResourceManager.GetString("LABEL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key d_irectory:.
        /// </summary>
        public static string LABEL_KEY_DIRECTORY {
            get {
                return ResourceManager.GetString("LABEL_KEY_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Login:.
        /// </summary>
        public static string LABEL_LOGIN {
            get {
                return ResourceManager.GetString("LABEL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Master password:.
        /// </summary>
        public static string LABEL_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New master password:.
        /// </summary>
        public static string LABEL_NEW_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_NEW_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_urrent master password:.
        /// </summary>
        public static string LABEL_OLD_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_OLD_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Password:.
        /// </summary>
        public static string LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password _file:.
        /// </summary>
        public static string LABEL_PASSWORD_FILE {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reenter password after (seconds):.
        /// </summary>
        public static string LABEL_REENTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_REENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select key directory..
        /// </summary>
        public static string LABEL_SELECT_KEY_DIRECTORY {
            get {
                return ResourceManager.GetString("LABEL_SELECT_KEY_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _windows always in front.
        /// </summary>
        public static string LABEL_TOPMOST {
            get {
                return ResourceManager.GetString("LABEL_TOPMOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _URL:.
        /// </summary>
        public static string LABEL_URL {
            get {
                return ResourceManager.GetString("LABEL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MENUITEM_EDIT {
            get {
                return ResourceManager.GetString("MENUITEM_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MENUITEM_FILE {
            get {
                return ResourceManager.GetString("MENUITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MENUITEM_HELP {
            get {
                return ResourceManager.GetString("MENUITEM_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MENUITEM_VIEW {
            get {
                return ResourceManager.GetString("MENUITEM_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the selected items?.
        /// </summary>
        public static string QUESTION_DELETE_ITEMS {
            get {
                return ResourceManager.GetString("QUESTION_DELETE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes?.
        /// </summary>
        public static string QUESTION_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("QUESTION_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} items selected..
        /// </summary>
        public static string SELECTED_0_OF_1 {
            get {
                return ResourceManager.GetString("SELECTED_0_OF_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 item selected..
        /// </summary>
        public static string SELECTED_ONE {
            get {
                return ResourceManager.GetString("SELECTED_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2017-2020 Niels Stockfleth
        ///
        ///This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more deta [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TEXT_COPYRIGHT {
            get {
                return ResourceManager.GetString("TEXT_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search list.
        /// </summary>
        public static string TEXT_SEARCH_LIST {
            get {
                return ResourceManager.GetString("TEXT_SEARCH_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string TITLE_ADD {
            get {
                return ResourceManager.GetString("TITLE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change master password.
        /// </summary>
        public static string TITLE_CHANGE_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_CHANGE_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload passwords into cloud.
        /// </summary>
        public static string TITLE_CLOUD_UPLOAD {
            get {
                return ResourceManager.GetString("TITLE_CLOUD_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TITLE_EDIT {
            get {
                return ResourceManager.GetString("TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password file.
        /// </summary>
        public static string TITLE_NEW {
            get {
                return ResourceManager.GetString("TITLE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Manager.
        /// </summary>
        public static string TITLE_PASSWORD_MANAGER {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string TITLE_PROPERTIES {
            get {
                return ResourceManager.GetString("TITLE_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TITLE_SETTINGS {
            get {
                return ResourceManager.GetString("TITLE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string TOOLTIP_ADD {
            get {
                return ResourceManager.GetString("TOOLTIP_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy login to clipboard.
        /// </summary>
        public static string TOOLTIP_COPY_LOGIN {
            get {
                return ResourceManager.GetString("TOOLTIP_COPY_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy password to clipboard.
        /// </summary>
        public static string TOOLTIP_COPY_PASSWORD {
            get {
                return ResourceManager.GetString("TOOLTIP_COPY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string TOOLTIP_DELETE {
            get {
                return ResourceManager.GetString("TOOLTIP_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TOOLTIP_EDIT {
            get {
                return ResourceManager.GetString("TOOLTIP_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start password generator.
        /// </summary>
        public static string TOOLTIP_GENERATE_PASSWORD {
            get {
                return ResourceManager.GetString("TOOLTIP_GENERATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide password.
        /// </summary>
        public static string TOOLTIP_HIDE_PASSWORD {
            get {
                return ResourceManager.GetString("TOOLTIP_HIDE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string TOOLTIP_NEW {
            get {
                return ResourceManager.GetString("TOOLTIP_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string TOOLTIP_OPEN {
            get {
                return ResourceManager.GetString("TOOLTIP_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open URL in browser.
        /// </summary>
        public static string TOOLTIP_OPEN_URL {
            get {
                return ResourceManager.GetString("TOOLTIP_OPEN_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TOOLTIP_SAVE {
            get {
                return ResourceManager.GetString("TOOLTIP_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string TOOLTIP_SHOW_PASSWORD {
            get {
                return ResourceManager.GetString("TOOLTIP_SHOW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items..
        /// </summary>
        public static string TOTAL_0 {
            get {
                return ResourceManager.GetString("TOTAL_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 item..
        /// </summary>
        public static string TOTAL_ONE {
            get {
                return ResourceManager.GetString("TOTAL_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify password.
        /// </summary>
        public static string VERIFY_PASSWORD {
            get {
                return ResourceManager.GetString("VERIFY_PASSWORD", resourceCulture);
            }
        }
    }
}
