//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear clipboard in {0} seconds. ähnelt.
        /// </summary>
        public static string AUTO_CLEAR_CLIPBOARD_IN_0 {
            get {
                return ResourceManager.GetString("AUTO_CLEAR_CLIPBOARD_IN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear clipboard in 1 second. ähnelt.
        /// </summary>
        public static string AUTO_CLEAR_CLIPBOARD_IN_ONE {
            get {
                return ResourceManager.GetString("AUTO_CLEAR_CLIPBOARD_IN_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide password in {0} seconds. ähnelt.
        /// </summary>
        public static string AUTO_HIDE_IN_0 {
            get {
                return ResourceManager.GetString("AUTO_HIDE_IN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide password in 1 second. ähnelt.
        /// </summary>
        public static string AUTO_HIDE_IN_ONE {
            get {
                return ResourceManager.GetString("AUTO_HIDE_IN_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Cancel ähnelt.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cop_y password ähnelt.
        /// </summary>
        public static string BUTTON_COPY_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_COPY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _New password ähnelt.
        /// </summary>
        public static string BUTTON_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _OK ähnelt.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _About... ähnelt.
        /// </summary>
        public static string CMD_ABOUT {
            get {
                return ResourceManager.GetString("CMD_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Add... ähnelt.
        /// </summary>
        public static string CMD_ADD {
            get {
                return ResourceManager.GetString("CMD_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change _key directory... ähnelt.
        /// </summary>
        public static string CMD_CHANGE_KEY_DIRECTORY {
            get {
                return ResourceManager.GetString("CMD_CHANGE_KEY_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change _master password... ähnelt.
        /// </summary>
        public static string CMD_CHANGE_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_CHANGE_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Close ähnelt.
        /// </summary>
        public static string CMD_CLOSE {
            get {
                return ResourceManager.GetString("CMD_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy _login to clipboard ähnelt.
        /// </summary>
        public static string CMD_COPY_LOGIN {
            get {
                return ResourceManager.GetString("CMD_COPY_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy _password to clipboard ähnelt.
        /// </summary>
        public static string CMD_COPY_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_COPY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Remove ähnelt.
        /// </summary>
        public static string CMD_DELETE {
            get {
                return ResourceManager.GetString("CMD_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit... ähnelt.
        /// </summary>
        public static string CMD_EDIT {
            get {
                return ResourceManager.GetString("CMD_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E_xit ähnelt.
        /// </summary>
        public static string CMD_EXIT {
            get {
                return ResourceManager.GetString("CMD_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start password _generator ähnelt.
        /// </summary>
        public static string CMD_GENERATE_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_GENERATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die H_ide password ähnelt.
        /// </summary>
        public static string CMD_HIDE_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_HIDE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _New... ähnelt.
        /// </summary>
        public static string CMD_NEW {
            get {
                return ResourceManager.GetString("CMD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Open... ähnelt.
        /// </summary>
        public static string CMD_OPEN {
            get {
                return ResourceManager.GetString("CMD_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Open URL in browser ähnelt.
        /// </summary>
        public static string CMD_OPEN_URL {
            get {
                return ResourceManager.GetString("CMD_OPEN_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Properties... ähnelt.
        /// </summary>
        public static string CMD_PROPERTIES {
            get {
                return ResourceManager.GetString("CMD_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Save ähnelt.
        /// </summary>
        public static string CMD_SAVE {
            get {
                return ResourceManager.GetString("CMD_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save _As... ähnelt.
        /// </summary>
        public static string CMD_SAVE_AS {
            get {
                return ResourceManager.GetString("CMD_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show _login column ähnelt.
        /// </summary>
        public static string CMD_SHOW_LOGIN_COLUMN {
            get {
                return ResourceManager.GetString("CMD_SHOW_LOGIN_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Show password ähnelt.
        /// </summary>
        public static string CMD_SHOW_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_SHOW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show pass_word column ähnelt.
        /// </summary>
        public static string CMD_SHOW_PASSWORD_COLUMN {
            get {
                return ResourceManager.GetString("CMD_SHOW_PASSWORD_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string COLUMN_LOGIN {
            get {
                return ResourceManager.GetString("COLUMN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string COLUMN_NAME {
            get {
                return ResourceManager.GetString("COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string COLUMN_PASSWORD {
            get {
                return ResourceManager.GetString("COLUMN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected file has the wrong format. ähnelt.
        /// </summary>
        public static string ERROR_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The key for &apos;{0}&apos; does not exist in the directory &apos;{1}&apos;. ähnelt.
        /// </summary>
        public static string ERROR_KEY_NOT_FOUND_0_1 {
            get {
                return ResourceManager.GetString("ERROR_KEY_NOT_FOUND_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred. {0} ähnelt.
        /// </summary>
        public static string ERROR_OCCURRED_0 {
            get {
                return ResourceManager.GetString("ERROR_OCCURRED_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password does not match. ähnelt.
        /// </summary>
        public static string ERROR_PASSWORD_DOES_NOT_MATCH {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_DOES_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password must contain at least 4 characters. ähnelt.
        /// </summary>
        public static string ERROR_PASSWORD_MIN_CHARS {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_MIN_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid input values for the password generation. ähnelt.
        /// </summary>
        public static string ERROR_PWDGEN_INVALID_INPUT {
            get {
                return ResourceManager.GetString("ERROR_PWDGEN_INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password is wrong. ähnelt.
        /// </summary>
        public static string ERROR_WRONG_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_WRONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password files (*.pwd)|*.pwd|All files (*.*)|*.* ähnelt.
        /// </summary>
        public static string FILE_DIALOG_FILTER {
            get {
                return ResourceManager.GetString("FILE_DIALOG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm m_aster password: ähnelt.
        /// </summary>
        public static string LABEL_CONFIRM_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_onfirm new master password: ähnelt.
        /// </summary>
        public static string LABEL_CONFIRM_NEW_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_NEW_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm passw_ord: ähnelt.
        /// </summary>
        public static string LABEL_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Description: ähnelt.
        /// </summary>
        public static string LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Digits ähnelt.
        /// </summary>
        public static string LABEL_DIGITS {
            get {
                return ResourceManager.GetString("LABEL_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the master password for &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string LABEL_ENTER_MASTER_PASSWORD_FOR_0 {
            get {
                return ResourceManager.GetString("LABEL_ENTER_MASTER_PASSWORD_FOR_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key: ähnelt.
        /// </summary>
        public static string LABEL_KEY {
            get {
                return ResourceManager.GetString("LABEL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key d_irectory: ähnelt.
        /// </summary>
        public static string LABEL_KEY_DIRECTORY {
            get {
                return ResourceManager.GetString("LABEL_KEY_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Login: ähnelt.
        /// </summary>
        public static string LABEL_LOGIN {
            get {
                return ResourceManager.GetString("LABEL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lo_wer characters: ähnelt.
        /// </summary>
        public static string LABEL_LOWER_CHARS {
            get {
                return ResourceManager.GetString("LABEL_LOWER_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Master password: ähnelt.
        /// </summary>
        public static string LABEL_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Name: ähnelt.
        /// </summary>
        public static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _New master password: ähnelt.
        /// </summary>
        public static string LABEL_NEW_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_NEW_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_urrent master password: ähnelt.
        /// </summary>
        public static string LABEL_OLD_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_OLD_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Password: ähnelt.
        /// </summary>
        public static string LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password _file: ähnelt.
        /// </summary>
        public static string LABEL_PASSWORD_FILE {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password _length: ähnelt.
        /// </summary>
        public static string LABEL_PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select key directory. ähnelt.
        /// </summary>
        public static string LABEL_SELECT_KEY_DIRECTORY {
            get {
                return ResourceManager.GetString("LABEL_SELECT_KEY_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Symbols: ähnelt.
        /// </summary>
        public static string LABEL_SYMBOLS {
            get {
                return ResourceManager.GetString("LABEL_SYMBOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Upper characters: ähnelt.
        /// </summary>
        public static string LABEL_UPPER_CHARS {
            get {
                return ResourceManager.GetString("LABEL_UPPER_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _URL: ähnelt.
        /// </summary>
        public static string LABEL_URL {
            get {
                return ResourceManager.GetString("LABEL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit ähnelt.
        /// </summary>
        public static string MENUITEM_EDIT {
            get {
                return ResourceManager.GetString("MENUITEM_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _File ähnelt.
        /// </summary>
        public static string MENUITEM_FILE {
            get {
                return ResourceManager.GetString("MENUITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Help ähnelt.
        /// </summary>
        public static string MENUITEM_HELP {
            get {
                return ResourceManager.GetString("MENUITEM_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _View ähnelt.
        /// </summary>
        public static string MENUITEM_VIEW {
            get {
                return ResourceManager.GetString("MENUITEM_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the selected items? ähnelt.
        /// </summary>
        public static string QUESTION_DELETE_ITEMS {
            get {
                return ResourceManager.GetString("QUESTION_DELETE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save the changes? ähnelt.
        /// </summary>
        public static string QUESTION_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("QUESTION_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of {1} items selected. ähnelt.
        /// </summary>
        public static string SELECTED_0_OF_1 {
            get {
                return ResourceManager.GetString("SELECTED_0_OF_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 item selected. ähnelt.
        /// </summary>
        public static string SELECTED_ONE {
            get {
                return ResourceManager.GetString("SELECTED_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright 2017 Niels Stockfleth
        ///
        ///This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. ähnelt.
        /// </summary>
        public static string TEXT_COPYRIGHT {
            get {
                return ResourceManager.GetString("TEXT_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search list ähnelt.
        /// </summary>
        public static string TEXT_SEARCH_LIST {
            get {
                return ResourceManager.GetString("TEXT_SEARCH_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string TITLE_ADD {
            get {
                return ResourceManager.GetString("TITLE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change master password ähnelt.
        /// </summary>
        public static string TITLE_CHANGE_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_CHANGE_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string TITLE_EDIT {
            get {
                return ResourceManager.GetString("TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate random password ähnelt.
        /// </summary>
        public static string TITLE_GENERATE_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_GENERATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New password file ähnelt.
        /// </summary>
        public static string TITLE_NEW {
            get {
                return ResourceManager.GetString("TITLE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password Manager ähnelt.
        /// </summary>
        public static string TITLE_PASSWORD_MANAGER {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        public static string TITLE_PROPERTIES {
            get {
                return ResourceManager.GetString("TITLE_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string TOOLTIP_ADD {
            get {
                return ResourceManager.GetString("TOOLTIP_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string TOOLTIP_DELETE {
            get {
                return ResourceManager.GetString("TOOLTIP_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string TOOLTIP_EDIT {
            get {
                return ResourceManager.GetString("TOOLTIP_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide password ähnelt.
        /// </summary>
        public static string TOOLTIP_HIDE_PASSWORD {
            get {
                return ResourceManager.GetString("TOOLTIP_HIDE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string TOOLTIP_NEW {
            get {
                return ResourceManager.GetString("TOOLTIP_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string TOOLTIP_OPEN {
            get {
                return ResourceManager.GetString("TOOLTIP_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open URL in browser ähnelt.
        /// </summary>
        public static string TOOLTIP_OPEN_URL {
            get {
                return ResourceManager.GetString("TOOLTIP_OPEN_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string TOOLTIP_SAVE {
            get {
                return ResourceManager.GetString("TOOLTIP_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show password ähnelt.
        /// </summary>
        public static string TOOLTIP_SHOW_PASSWORD {
            get {
                return ResourceManager.GetString("TOOLTIP_SHOW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} items. ähnelt.
        /// </summary>
        public static string TOTAL_0 {
            get {
                return ResourceManager.GetString("TOTAL_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 item. ähnelt.
        /// </summary>
        public static string TOTAL_ONE {
            get {
                return ResourceManager.GetString("TOTAL_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verify password ähnelt.
        /// </summary>
        public static string VERIFY_PASSWORD {
            get {
                return ResourceManager.GetString("VERIFY_PASSWORD", resourceCulture);
            }
        }
    }
}
