name: Release Myna PasswordManager
on:
  push:
   tags:
      - "v*"
jobs:
  build:
    runs-on: windows-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: bin/Release/net8.0-windows/publish
    - name: Create release ZIP file
      run: Compress-Archive -Path bin/Release/net8.0-windows/publish/* -Destination "MynaPasswordManager-${{ github.ref_name }}.zip"
    - name: Create github release
      run: gh release create "${{ github.ref_name }}" "MynaPasswordManager-${{ github.ref_name }}.zip"
